BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Menu" (
	"Item"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Price"	NUMERIC NOT NULL,
	PRIMARY KEY("Item")
);
CREATE TABLE IF NOT EXISTS "Orders" (
	"Item"	INTEGER,
	"Qty"	INTEGER NOT NULL,
	"Total Bill"	INTEGER NOT NULL,
	"OrderNo"	INTEGER NOT NULL,
	PRIMARY KEY("OrderNo"),
	FOREIGN KEY("Item") REFERENCES "Menu"("Item")
);
CREATE TABLE IF NOT EXISTS "Report" (
	"Item"	INTEGER NOT NULL,
	"Sold"	INTEGER NOT NULL,
	FOREIGN KEY("Item") REFERENCES "Orders"("Item")
);
CREATE TABLE IF NOT EXISTS "users" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL,
	"Password"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
INSERT INTO "Menu" VALUES (1,'Rice \w Curry',100);
INSERT INTO "Menu" VALUES (2,'Parota ( 1pcs )',20);
INSERT INTO "Menu" VALUES (4,'Rotti ( 1pcs )',20);
INSERT INTO "Menu" VALUES (6,'Milk Tea',80);
INSERT INTO "Menu" VALUES (7,'Ice Packet',20);
INSERT INTO "users" VALUES (1,'admin','5f4dcc3b5aa765d61d8327deb882cf99');
INSERT INTO "users" VALUES (2,'manager','5f4dcc3b5aa765d61d8327deb882cf99');
COMMIT;
